#端口号
server:
  port: 80

spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.95.239:3306/baiduwf?useunicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: scaubaiduWF123!
  #mvc
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true
